Comment out heart + comment icons
concrete5/documentation.concretecms.org pull request #4
Opened 2021-04-28 16:29 UTC by bitterdev

2021-04-28 17:41 UTC, aembler commented
We should use PHP comments on this or remove it entirely so that it doesn't actually do all the database queries.

2021-04-28 17:42 UTC, aembler requested changes
Please see the previous comment.

2021-04-29 18:57 UTC, bitterdev commented
@aembler Hi Andrew i have used the php comment function like required.

2021-05-01 00:09 UTC, aembler requested changes

2021-05-01 00:09 UTC, aembler commented on public/packages/concrete_cms_docs/blocks/tutorial_list/view.php
> +                                    <!--
I think you missed this one

2021-05-02 09:50 UTC, bitterdev commented on public/packages/concrete_cms_docs/blocks/tutorial_list/view.php
> +                                    <!--
i have fixed it thank you

2021-05-04 22:32 UTC, merged